default_target: all

all: word_frequencies intersection_of_two_files

word_frequencies:
	$(CXX) -Wall --std=c++11 -o word_frequencies word_frequencies.cxx

intersection_of_two_files:
	$(CXX) -Wall --std=c++11 -o intersection_of_two_files intersection_of_two_files.cxx

clean:
	-rm word_frequencies
	-rm intersection_of_two_files
